language: node_js
node_js:
- 7.10.0
branches:
  only:
  - master

before_install:
- openssl aes-256-cbc -K $encrypted_862bac004353_key -iv $encrypted_862bac004353_iv
  -in id_rsa.enc -out id_rsa -d




