language: node_js
node_js:
- 7.10.0
branches:
  only:
  - master
after_script: -scp -o StrictHostKeyChecking=no app.js root@123.207.233.35:/home/www/ceshi
dd:
- openssl aes-256-cbc -K $encrypted_e16011055c45_key -iv $encrypted_e16011055c45_iv
  -in id_rsa.enc -out id_rsa -d

- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
