language: node_js
node_js:
- 7.10.0
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_862bac004353_key -iv $encrypted_862bac004353_iv
  -in travis_demo.enc -out ~/.ssh/travis_demo -d

- chmod 600 ~/.ssh/travis_demo
- eval $(ssh-agent)
- ssh-add ~/.ssh/travis_demo
- cp .travis/ssh_config ~/.ssh/config

after_script: 
- scp -o StrictHostKeyChecking=no app.js root@47.93.58.173:/home/www/ceshi
